### ISSUE TITLE
oneview_logical_interconnect_group resource not updating

### ISSUE THREAD

**Issue by riconem** [HewlettPackard/oneview-puppet#238]
### Scenario/Intent
When I created a Logical Interconnect Group resource with several uplinkSets and want to delete some of them, Puppet don't delete them. For Puppet it looks like there are no changes, but in Oneview the UplinkSet is still there.

### Environment Details
 - **Puppet module for HPE OneView Version:** v2.4.0
 - **OneView SDK Version:** 5.10.0
 - **OneView Appliance Version:** 5.00.00.02-0404934
 - **OneView Client API Version:** 1000
 - **Puppet Version:** 5.5.17
 - **Ruby Version:** 2.4.5
 - **Platform:** Oracle Linux Server 7.7

### Steps to Reproduce
Create a Logical Interconnect Group resource like this with puppet (works):
```yaml
oneviewconf::oneview_logical_interconnect_group:
  Puppet_LIG:
    ensure: present
    data:
      name: Puppet_LIG
      enclosureType: SY12000
      enclosureIndexes:
      - 1
      interconnectBaySet: 3
      redundancyType: NonRedundantASide
      interconnects:
      - bay: 3
        type: Virtual Connect SE 40Gb F8 Module for Synergy
        enclosure_index: 1
      uplinkSets:
      - name: Uplink_Ethernet
        networkType: Ethernet
        mode: Auto
        lacpTimer: Short
        uplink_ports:
        - bay: 3
          port: Q1:1
          enclosure_index: 1
          type: Virtual Connect SE 40Gb F8 Module for Synergy
      -
        name: 'Uplink_SAN'
        networkType: 'FibreChannel'
        uplink_ports:
        -
          bay: 3
          port: 'Q2:1'
          type: Virtual Connect SE 40Gb F8 Module for Synergy
          enclosure_index: 1
```
Delete `Uplink_SAN` in `uplinkSets` and re-run Puppet (nothing changes):
```yaml
oneviewconf::oneview_logical_interconnect_group:
  Puppet_LIG:
    ensure: present
    data:
      name: Puppet_LIG
      enclosureType: SY12000
      enclosureIndexes:
      - 1
      interconnectBaySet: 3
      redundancyType: NonRedundantASide
      interconnects:
      - bay: 3
        type: Virtual Connect SE 40Gb F8 Module for Synergy
        enclosure_index: 1
      uplinkSets:
      - name: Uplink_Ethernet
        networkType: Ethernet
        mode: Auto
        lacpTimer: Short
        uplink_ports:
        - bay: 3
          port: Q1:1
          enclosure_index: 1
          type: Virtual Connect SE 40Gb F8 Module for Synergy
```

### Expected Result
Updating Logical Interconnect Group Resource in Oneview.

### Actual Result
Nothing changes in Oneview.
