### ISSUE TITLE
Failing to create oneview_server_profile_tempate with connections

### ISSUE THREAD

**Issue by riconem** [HewlettPackard/oneview-puppet#315]
### Scenario/Intent
Creating a `oneview_server_profile_template` resource with `connections`.

### Environment Details
 - **Puppet module for HPE OneView Version:** v2.9.0
 - **OneView SDK Version:** 5.17.0
 - **OneView Appliance Version:**  5.50.00-0426657
 - **OneView Client API Version:** 1200
 - **Puppet Version:** 5.5.17
 - **Ruby Version:** 2.4.5
 - **Platform:** Oracle Linux Server 7.7

### Steps to Reproduce
Create a `oneview_server_profile_template` resource with the following parameters.

```yaml
#  SY 480 Gen9, Enclosure_Group_01 and Network_Set_01 are required
oneviewconf::dtt::server_profile_templates:
  ESX_Server_Template:
    serverHardwareTypeUri: SY 480 Gen9
    affinity: Bay
    hideUnusedFlexNics: true
    macType: Virtual
    wwnType: Virtual
    serialNumberType: Virtual
    enclosureGroupUri: Enclosure_Group_01
    connectionSettings:
      complianceControl: Checked
      manageConnections: true
      connections:
      - id: 1
        functionType: Set
        networkUri: Network_Set_01
        portId: Mezz 3:1-a
        requestedVFs: 0
        requestedMbps: 2000
        boot:
           priority: NotBootable
        isolatedTrunk: false
    bootMode:
      complianceControl: Checked
      manageMode: true
      mode: BIOS
      secureBoot: Disabled
    boot:
      complianceControl: Checked
      manageBoot: true
      order:
        - CD
        - USB
        - HardDisk
        - PXE
    bios:
      complianceControl: Checked
      manageBios: true
```

### Expected Result
Creating  one `oneview_server_profile_template` resource with `connections`.

### Actual Result
The following Error pops up in the console.
```
Error: /Stage[main]/Oneviewconf::Dtt/Oneview_server_profile_template[ESX_Server_Template]: Could not evaluate: undefined method `include?' for true:TrueClass
```
