### ISSUE TITLE
Failing to change a serverProfileTemplateUri from a serverProfile resource

### ISSUE THREAD

**Issue by riconem** [HewlettPackard/oneview-puppet#322]
### Scenario/Intent
Edit the current `serverProfileTemplateUri` from a `oneview_server_profile` resource.

### Environment Details
 - **Puppet module for HPE OneView Version:** v2.9.1(Unreleased)
 - **OneView SDK Version:** 5.17.0
 - **OneView Appliance Version:**  5.50.00-0426657
 - **OneView Client API Version:** 1200
 - **Puppet Version:** 5.5.17
 - **Ruby Version:** 2.4.5
 - **Platform:** Oracle Linux Server 7.7

### Steps to Reproduce
Create some `oneview_server_profile_template` resources and some `oneview_server_profile` resources based on `oneview_server_profile_template` resources like in the following code.
```yaml
oneviewconf::oneview::server_profile_templates:
  ESX_template_AA:
    ensure: present
    data:
      name: ESX_template_AA
      serverHardwareTypeUri: SY 480 Gen9 mit SAS
      affinity: Bay
      hideUnusedFlexNics: true
      macType: Virtual
      wwnType: Virtual
      serialNumberType: Virtual
      enclosureGroupUri: Enclosure_Group
      connectionSettings:
        complianceControl: Checked
        manageConnections: true
        connections:
        - id: 1
          functionType: Set
          networkUri: Network_Set_01
          portId: Mezz 3:1-a
          requestedVFs: 0
          requestedMbps: 2000
          boot:
            priority: NotBootable
          isolatedTrunk: false
      bootMode:
        complianceControl: Checked
        manageMode: true
        mode: BIOS
        secureBoot: Disabled
      boot:
        complianceControl: Checked
        manageBoot: true
        order:
          - CD
          - USB
          - HardDisk
          - PXE
      bios:
        complianceControl: Checked
        manageBios: true
  ESX_template_BB:
    ensure: present
    data:
      name: ESX_template_BB
      serverHardwareTypeUri: SY 480 Gen9 mit SAS
      affinity: Bay
      hideUnusedFlexNics: true
      macType: Virtual
      wwnType: Virtual
      serialNumberType: Virtual
      enclosureGroupUri: Enclosure_Group
      connectionSettings:
        complianceControl: Checked
        manageConnections: true
        connections:
        - id: 1
          functionType: Set
          networkUri: Network_Set_02
          portId: Mezz 3:1-a
          requestedVFs: 0
          requestedMbps: 2000
          boot:
            priority: NotBootable
          isolatedTrunk: false
      bootMode:
        complianceControl: Checked
        manageMode: true
        mode: BIOS
        secureBoot: Disabled
      boot:
        complianceControl: Checked
        manageBoot: true
        order:
          - CD
          - USB
          - HardDisk
          - PXE
      bios:
        complianceControl: Checked
        manageBios: true
  server_profile_AA_from_template:
    require: Oneview_server_profile_template[ESX_template_AA]
    ensure: set_new_profile
    data:
      name: ESX_template_AA
      serverProfileName: server_profile_AA
  server_profile_BB_from_template:
    require: Oneview_server_profile_template[ESX_template_BB]
    ensure: set_new_profile
    data:
      name: ESX_template_BB
      serverProfileName: server_profile_BB
```

Now I want to change the `serverProfileTemplateUri` to another Template in the `server_profile_AA`. I tried the following code in another run.
```yaml
oneviewconf::oneview::server_profiles:
  server_profile_BB:
    ensure: present
    data:
      name: server_profile_BB
      serverProfileTemplateUri: ESX_template_BB
  server_profile_AA:
    ensure: present
    data:
      name: server_profile_AA
      serverProfileTemplateUri: ESX_template_BB
```

I though this is a legitimate operation because it is also documented in the Oneview REST-API documentation.
![server_profiles](https://user-images.githubusercontent.com/27899109/107631400-344eac80-6c65-11eb-876b-561571f48f8e.PNG)
![serverTemplate](https://user-images.githubusercontent.com/27899109/107631403-37499d00-6c65-11eb-971b-f9b73c36f8b0.PNG)

### Expected Result
Changing the current `serverProfileTemplateUri` from the `oneview_server_profile` resource.

### Actual Result
```
Error: Could not set 'present' on ensure: Please set uri attribute before interacting with this resource (file: /etc/puppetlabs/code/environments/en_oneviewconf/site/oneviewconf/manifests/oneview.pp, line: 186)
Error: Could not set 'present' on ensure: Please set uri attribute before interacting with this resource (file: /etc/puppetlabs/code/environments/en_oneviewconf/site/oneviewconf/manifests/oneview.pp, line: 186)
Wrapped exception:
Please set uri attribute before interacting with this resource
Error: /Stage[main]/Oneviewconf::Oneview/Oneview_server_profile[server_profile_AA]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: Please set uri attribute before interacting with this resource (file: /etc/puppetlabs/code/environments/en_oneviewconf/site/oneviewconf/manifests/oneview.pp, line: 186)
```

### Quickfix and Guess
I looked up the exception in the error code. It comes from the oneview-ruby-sdk. The following function is used severel times to create, delete or update resources.
```ruby
    # Fail unless @data['uri'] is set for this resource.
    def ensure_uri
      raise IncompleteResource, 'Please set uri attribute before interacting with this resource' unless @data['uri']
      true
    end
```
https://github.com/HewlettPackard/oneview-sdk-ruby/blob/0e2a35efbaf64bef11a98ebf5263af2a9782ed9b/lib/oneview-sdk/resource.rb#L374

I also noticed the following snippet inside the `oneview_server_profile` provider. This should get all the data of the template, merge it with the current data and returns it.
https://github.com/HewlettPackard/oneview-puppet/blob/021653a7d06de77e80df6311da114b05808f857a/lib/puppet/provider/oneview_server_profile/c7000.rb#L31
I printed out what happend in that function. Here is the output.
```
data output before function:
{"name"=>"server_profile_AA",
 "serverProfileTemplateUri"=>
  "/rest/server-profile-templates/39f1602f-7fac-4496-9375-5c3683210371"}

data output afterfunction:
{"type"=>"ServerProfileV11",
 "uri"=>nil,
 "name"=>"server_profile_AA",
 "description"=>"",
 "serialNumber"=>nil,
 "uuid"=>nil,
 "iscsiInitiatorName"=>nil,
 "iscsiInitiatorNameType"=>"AutoGenerated",
 "serverProfileTemplateUri"=>
  "/rest/server-profile-templates/39f1602f-7fac-4496-9375-5c3683210371",
 "templateCompliance"=>"Unknown",
 "serverHardwareUri"=>nil,
 "serverHardwareTypeUri"=>
  "/rest/server-hardware-types/F61842E9-0636-40D7-9971-3B6A11399E16",
 "enclosureGroupUri"=>
  "/rest/enclosure-groups/495b5eb4-1c7f-459d-ab39-5afc677079af",
 "enclosureUri"=>nil,
 "enclosureBay"=>nil,
 "affinity"=>"Bay",
 "associatedServer"=>nil,
 "hideUnusedFlexNics"=>true,
 "firmware"=>
  {"firmwareBaselineUri"=>nil,
   "manageFirmware"=>false,
   "forceInstallFirmware"=>false,
   "firmwareInstallType"=>nil,
   "firmwareScheduleDateTime"=>"",
   "firmwareActivationType"=>nil,
   "reapplyState"=>"NotApplying",
   "consistencyState"=>"Unknown"},
 "macType"=>"Virtual",
 "wwnType"=>"Virtual",
 "serialNumberType"=>"Virtual",
 "category"=>"server-profiles",
 "created"=>nil,
 "modified"=>nil,
 "status"=>"OK",
 "state"=>"Creating",
 "serverHardwareReapplyState"=>"NotApplying",
 "inProgress"=>false,
 "taskUri"=>nil,
 "connectionSettings"=>
  {"reapplyState"=>"NotApplying",
   "connections"=>
    [{"id"=>1,
      "name"=>nil,
      "functionType"=>"Ethernet",
      "networkUri"=>"/rest/network-sets/e81fc300-9fcd-4875-8f8b-951e2714408b",
      "portId"=>"Mezz 3:1-a",
      "requestedVFs"=>"0",
      "allocatedVFs"=>nil,
      "interconnectUri"=>nil,
      "macType"=>nil,
      "wwpnType"=>nil,
      "mac"=>nil,
      "wwnn"=>nil,
      "wwpn"=>nil,
      "requestedMbps"=>"2000",
      "allocatedMbps"=>0,
      "maximumMbps"=>0,
      "ipv4"=>nil,
      "boot"=>{"priority"=>"NotBootable"},
      "state"=>"Unknown",
      "status"=>"Unknown",
      "managed"=>true,
      "networkName"=>nil,
      "lagName"=>nil,
      "interconnectPort"=>0,
      "isolatedTrunk"=>false,
      "privateVlanPortType"=>"None"}]},
 "bootMode"=>
  {"manageMode"=>true,
   "mode"=>"BIOS",
   "pxeBootPolicy"=>nil,
   "secureBoot"=>"Disabled"},
 "boot"=>{"manageBoot"=>true, "order"=>["CD", "USB", "HardDisk", "PXE"]},
 "bios"=>
  {"manageBios"=>true,
   "overriddenSettings"=>[],
   "reapplyState"=>"NotApplying",
   "consistencyState"=>"Unknown"},
 "managementProcessor"=>
  {"reapplyState"=>"NotApplying", "manageMp"=>false, "mpSettings"=>[]},
 "localStorage"=>
  {"sasLogicalJBODs"=>[], "controllers"=>[], "reapplyState"=>"NotApplying"},
 "sanStorage"=>
  {"manageSanStorage"=>false,
   "volumeAttachments"=>[],
   "sanSystemCredentials"=>[],
   "reapplyState"=>"NotApplying"},
 "osDeploymentSettings"=>nil,
 "eTag"=>nil,
 "refreshState"=>"NotRefreshing"}
```
This data is returned when a `oneview_server_profile` resource is updated by puppet, but these parameters are not correct. You can see that on the `uri  => nil` because our `oneview_server_profile` has already an URI. 
So I deleted this function and everything works fine and I could change the `serverProfileTemplateUri`.

**New `oneview_server_profile` provider that works**
```ruby
# oneview-puppet/lib/puppet/provider/oneview_server_profile/c7000.rb
  def exists?
    prepare_environment
    #load_template(@data['serverProfileTemplateUri'], 'new_profile')
    return @resource_type.find_by(@client, @data).any? if resource['ensure'].to_sym == :absent
    super([nil, :found, :get_available_targets, :get_available_networks, :get_available_servers, :get_compliance_preview,
           :get_messages, :get_profile_ports, :get_transformation, :absent])
  end
```
