### ISSUE TITLE
Failing to create oneview_enclosure_group resources with interconnectBayMappings in v2.10.0

### ISSUE THREAD

**Issue by riconem** [HewlettPackard/oneview-puppet#330]
### Scenario/Intent
Trying to create a `oneview_enclosure_group` with `interconnectBayMappings`.

### Environment Details
 - **Puppet module for HPE OneView Version:** v2.10.0
 - **OneView SDK Version:** 5.17.0
 - **OneView Appliance Version:**  5.50.00-0426657
 - **OneView Client API Version:** 1200
 - **Puppet Version:** 5.5.17
 - **Ruby Version:** 2.4.5
 - **Platform:** Oracle Linux Server 7.7

### Steps to Reproduce
Create a `oneview_enclosure_group` resource like in the examples.
```yaml
oneviewconf::oneview::logical_interconnect_groups:
  LIG_01:
    ensure: present
    data:
      name: LIG_01
      enclosureType: SY12000
      consistencyCheckingForInternalNetworks: ExactMatch
      interconnectBaySet: 3
      enclosureIndexes:
      - 1
      redundancyType: Redundant
      interconnects:
      - bay: 6
        type: Virtual Connect SE 40Gb F8 Module for Synergy
        enclosure_index: 1
      - bay: 3
        type: Virtual Connect SE 40Gb F8 Module for Synergy
        enclosure_index: 1

oneviewconf::oneview::enclosure_groups:
  Enclosure_Group_Example:
    require: Oneview_logical_interconnect_group[LIG_01]
    ensure: present
    data:
      name: Enclosure_Group_Example
      stackingMode: Enclosure
      interconnectBayMappingCount: 2
      enclosureCount: 1
      interconnectBayMappings:
      - interconnectBay: 3
        logicalInterconnectGroupUri: LIG_01
      - interconnectBay: 6
        logicalInterconnectGroupUri: LIG_01
```

### Expected Result
Creation of a `oneview_enclosure_group` resource. 

### Actual Result
See Error Message:
```
Notice: /Stage[main]/Oneviewconf::Oneview/Oneview_logical_interconnect_group[LIG_01]/ensure: created
Error: /Stage[main]/Oneviewconf::Oneview/Oneview_enclosure_group[Enclosure_Group_Example]: Could not evaluate: undefined method `[]' for nil:NilClass
```

### Quick fix
The example worked for me in version v2.9.0. So the error must have come from new changes in v2.10.0.
In the `oneview_enclosure_group` [provider ](https://github.com/HewlettPackard/oneview-puppet/blob/9adeeacb0d333864b75946fb88c76a732251090c/lib/puppet/provider/oneview_enclosure_group/c7000.rb) were some changes. See the following.
```ruby
      lig_name = mapping_attr['logicalInterconnectGroupUri'] if mapping_attr['logicalInterconnectGroupUri']
      lig = OneviewSDK.resource_named(:LogicalInterconnectGroup, api_version, resource_variant).find_by(@client, name: lig_name)
      mapping_attr['logicalInterconnectGroupUri'] = lig.first['uri']
```
This code tries to to parse the `logicalInterconnectGroupUri` parameter but this is already done in the parent provider.
https://github.com/HewlettPackard/oneview-puppet/blob/9adeeacb0d333864b75946fb88c76a732251090c/lib/puppet/provider/oneview_resource.rb#L68

I printed out what the `@data` variable looks like at the beginning of the `data_parse` function in the `oneview_enclosure_group` provider. See the following.
```
{"name"=>"Enclosure_Group_Example",
 "stackingMode"=>"Enclosure",
 "interconnectBayMappingCount"=>2,
 "enclosureCount"=>1,
 "interconnectBayMappings"=>
  [{"interconnectBay"=>3,
    "logicalInterconnectGroupUri"=>
     "/rest/logical-interconnect-groups/7b24e8c5-e4f8-429d-88f1-641dac2c5503"},
   {"interconnectBay"=>6,
    "logicalInterconnectGroupUri"=>
     "/rest/logical-interconnect-groups/7b24e8c5-e4f8-429d-88f1-641dac2c5503"}]}
Error: /Stage[main]/Oneviewconf::Oneview/Oneview_enclosure_group[Enclosure_Group_Example]: Could not evaluate: undefined method `[]' for nil:NilClass
```
As you can see the parsing is already done and the `data_parse` function in the `oneview_enclosure_group` provider is not necessary. So I deleted that function completly and it worked. See the output.
```
Info: Performing create of EnclosureGroup Enclosure_Group_Example using the following data:
{
  "name": "Enclosure_Group_Example",
  "stackingMode": "Enclosure",
  "interconnectBayMappingCount": 2,
  "enclosureCount": 1,
  "interconnectBayMappings": [
    {
      "interconnectBay": 3,
      "logicalInterconnectGroupUri": "/rest/logical-interconnect-groups/7b24e8c5-e4f8-429d-88f1-641dac2c5503"
    },
    {
      "interconnectBay": 6,
      "logicalInterconnectGroupUri": "/rest/logical-interconnect-groups/7b24e8c5-e4f8-429d-88f1-641dac2c5503"
    }
  ]
}.
Notice: /Stage[main]/Oneviewconf::Oneview/Oneview_enclosure_group[Enclosure_Group_Example]/ensure: created
```
